name: ape-v2-base-strategy-adapter

plugins:
  - name: solidity
  - name: vyper
  - name: etherscan
  - name: hardhat
  - name: infura

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    ref: 4.7.1
  - name: yearnV2
    github: yearn/yearn-vaults
    ref: 0.4.6

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.1"
    - "@yearnV2=yearnV2/v0.4.6"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura